services:
  - type: web
    name: time-manager-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: FRONTEND_URL_PROD
        value: https://time-manager-frontend.onrender.com

  - type: web
    name: time-manager-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: free
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    envVars:
      - key: VITE_API_URL
        value: https://time-manager-backend.onrender.com